apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bncg0dn4a-python 
  janus-idp.io/tekton: bncg0dn4a-python
  backstage.io/kubernetes-id: bncg0dn4a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bncg0dn4a-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml